### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by hboetes** [bashgeek/icinga-multi-status#16]
If you use a https url and you are using a self signed certificate or one that doesn't match the certificate you get the message, and your new instance will be refused.
> unknown error

To work around that you will have to visit the API URL with a normal browser window first and import the certificate.

**Comment by bashgeek** [comment]
That is correct and mentioned in the help page and our readme very prominent. This is browser security behaviour we cannot, and honestly should not, be able override in any way.

A better way is to use proper signed certificates or adding your local CA's to your OS/browser properly.

**Comment by hboetes** [comment]
My point was the unspecific error message. A comprehensible errormessage would be nice.

**Comment by bashgeek** [comment]
Alright, fair enough. Changed the message a little, will be included in the next release. Thanks!
