### ISSUE TITLE
Mozilla Firefox 57 (Quantum) lost saved settings

### ISSUE THREAD

**Issue by tachtler** [bashgeek/icinga-multi-status#17]
Hi Daniel Schmitz,

I've installed icinga-multi-status at Mozilla Firefox 57 (Quantum), do my settings inside the Add-ons tab and save the settings.

After closing and starting Mozilla Firefox 57 (Quantum) again, all the settings of my Icinga instance will be lost and NO instance was set.

Please can you confirm that, or maybe I did something wrong on Mozilla Firefox 57 (Quantum) settings? So please can you help?

Thank you in advance.
Klaus.

**Comment by bashgeek** [comment]
Hello,
I tested this with Firefox 57 and it works fine for me and keeps all settings during restarts, so I'm unable to reconstruct your mentioned issue - also the first and only report about this. Maybe you run in private mode or have other addons blocking something? Can you try on a blank, new instance of Firefox?

Thanks for the report though.

**Comment by tachtler** [comment]
Hello,

I've tried it on Windows 10 with Firefox 57 and on Linux (CentOS) with Firefox 57 - on both installations - same result. After restart, the Instance settings are gone. On both test, I'm NOT using the private mode.

The only thing is, I changed the settings at (German) "Datenschutz & Sicherheit" to delete all data, when Firefox are closed. But that's not supposed to be the problem?

Maybe you can change here some settings too and try it again at your installation?

Thank you, for your time!
Klaus.

**Comment by tobias-bln** [comment]
Same on OSX. If you delete the history on exit and select cookies, website settings or offline website data, then the settings are gone at startup.
These settings work for me:

<img width="683" alt="ff-scrennshot2" src="https://user-images.githubusercontent.com/9417787/33204903-49b63826-d105-11e7-9abf-a57d3fdba668.png">
<img width="558" alt="ff-screenshot" src="https://user-images.githubusercontent.com/9417787/33204821-0939b30e-d105-11e7-93f0-90f7099096b5.png">

**Comment by tachtler** [comment]
Hi Tobias,

thank you for analyzing the problem. BUT the settings are NOT reasonable, because clearing the data while closing Firefox are important AND even worse are, that I have to accept cookies till they expire - thats NOT acceptable, because if the cookie expire on 31.12.9999 you will tracked from the website/owner of the cookie till the end of days.

So, thank you for your work to find out, under what circumstances the settings are gone - good work!

Klaus.

**Comment by tachtler** [comment]
Hi Daniel Schmitz,

meanwhile I'm not the only one with some Firefox setting that will delete the instance configuration from Firefox for the icinga-multi-status.

Can you tell me, what's the status of the project are, to solve the issue?

Thank you
Klaus.

**Comment by bashgeek** [comment]
I'm aware of this and know what is causing this (window.localStorage -> browser storage API). 

Unfortunately this will require quite some re-factoring on the internal settings handling and this will take some time. Time I currently don't have on my hands to put into open-source projects.

Feel free to rewrite this on your own and hand in a PR and support this project if you'd like. 

Otherwise, I hope I'll be able to squeeze some time in this year to implement this.

**Comment by tachtler** [comment]
Hi Daniel Schmitz,

thank you for your answer, I'm not familiar with that kind of programming, so I will, or have to wait, till you will find time for that issue.

But thank you in advance!
Klaus.

**Comment by HeadCrash66** [comment]
Hi,

I have the same problem of data/config loss if I'm closing Firefox.
Would be great if this issue can be fixed.
I like this add-on. It has a very nice GUI.

Thanks

**Comment by tachtler** [comment]
Hi Daniel Schmitz,

what about the status of rebuilding part of the code, to solve the problem?

Thank you, in advance!
Klaus.

**Comment by HeadCrash66** [comment]
@tgerling, many thanks your patch works like a charm.
I have testet and build my own xpi and all settings keeps stored after firefox is closed.

**Comment by bashgeek** [comment]
Thanks to the patch provided by @tgerling I was able to release a new version. I updated jQuery and Bootstrap along the way, so it also looks a little more modern. I consider this issue resolved now, sorry it took so long :-)
