### ISSUE TITLE
support old nagios (Nagios3) ?

### ISSUE THREAD

**Issue by michabbb** [bashgeek/icinga-multi-status#19]
hi,

is there any kind of support for old nagios systems where status gets fetched via:

`http://.........../cgi-bin/nagios3/status.cgi` ?

basic authentification seems not implemented here, so i guess not, but i wanted to ask ;)

thanks

**Comment by bashgeek** [comment]
Hi, we don't have a setup like this (not even Icinga v1 anymore, or knowing anymore who does) so I really couldn't implement it. But generally, sure, why not - even though the plugins is obviously meant for Icinga. Maybe you want to think about migrating to a more modern system? :-)

If you have time, abilities and want to contribute to the project, feel free to hand in a PR.

**Comment by michabbb** [comment]
it´s not always the developer who is able to make decisions about infrastructure. thanks ;)
