### ISSUE TITLE
Install from Chrome webstore broken

### ISSUE THREAD

**Issue by ethan-eb** [bashgeek/icinga-multi-status#2]
There appears to be a missing icon_48.png, see image:

![icinga-multi-status](https://cloud.githubusercontent.com/assets/2475518/8218731/b7a8e060-14f9-11e5-9a37-8667226f41cf.png)

**Comment by ethan-eb** [comment]
translation: the package is invalid. Details: "Extension icon could not be loaded "img/icon_48.png"."

**Comment by bashgeek** [comment]
Thanks for reporting, just fixed the package and re-uploaded it to the Web Store. Might take a little time to distribute.
