### ISSUE TITLE
What permission do i need?

### ISSUE THREAD

**Issue by bateau84** [bashgeek/icinga-multi-status#20]
Hey!  
So i want to create a API user and give specific permission. 
What permission does Icinga-multi-status require?

**Comment by bashgeek** [comment]
Hi, currently we're in read-only and running queries to the following API endpoints:
```
objects/hosts
objects/service
status/IcingaApplication
```

So this will probably end up in requiring the following permissions, for now:
```
objects/query/host
objects/query/service
status/query
```

**Comment by bateau84** [comment]
Cool, thanks. :+1: 
Would be nice to add this to the docs, maybe?
