### ISSUE TITLE
gret plugin ! one issue though

### ISSUE THREAD

**Issue by zibfr** [bashgeek/icinga-multi-status#21]
Hi guys,

just started using your great plugin.
I ve discovered one issue: 
- if host is DOWN and acknowledged, all related services are flaged as "Houston, we have a problem! 
Something seems broken, sorry."
in fact, all is green for me, but not for the plugin...
![image](https://user-images.githubusercontent.com/31119968/43613790-90a122ce-96fc-11e8-802b-17baa38d5375.png)

If you can correct or add an exclude option plz ?
Regards, 

Zibfr

**Comment by bashgeek** [comment]
Sorry for the late reply here.
We already have an ignore function for this in the instance setup: "Ignore acknowledged host & service problems", which should do what you're describing. Let me know if it doesn't.
