### ISSUE TITLE
"Houston, we have a problem! ..." - debugging options

### ISSUE THREAD

**Issue by MrRobbi** [bashgeek/icinga-multi-status#22]
Hiting "Save instance" gives: "Awesome! OK xxx hosts....*". Then when I open Icinga Multi Status I see "Houston, we have a problem! Something seems broken, sorry." 
How can I debug this?

**Comment by pcasis** [comment]
I guess "Houston, we have a problem! Something seems broken, sorry." means that something in your Icinga is in a Critical state.

**Comment by MrRobbi** [comment]
Not really :) It means that plugin can't connect to Icinga. I don't remember how but I did eventually manage to run plugin but it doesn't meet my needs.
