### ISSUE TITLE
Add Sound Notifications

### ISSUE THREAD

**Issue by sasha2002** [bashgeek/icinga-multi-status#23]
Hi,

It will be great to have some sound alerts when something is going bad.
Can someone add this sound alerts to the plugin?
Also it will be great if we can customize it via options, to upload our sounds

**Comment by Athanasius** [comment]
I'm just here to add a "me too!".  At least sashsa2002 saved me the typing ;) .

**Comment by dacrhu** [comment]
+1

**Comment by bashgeek** [comment]
Added with todays version v0.9.0, thanks :-)
