### ISSUE TITLE
icinga extension doesn't seem to work with Nagios anymore

### ISSUE THREAD

**Issue by thomasvs** [bashgeek/icinga-multi-status#26]
I think I've used it in the past to monitor Nagios instances, but doesn't seem to work anymore (hangs indefinitely when saving in the configuration)

If it used to work and doesn't anymore by design, I suggest that gets added to the README to avoid confusing people.

**Comment by bashgeek** [comment]
We never supported Nagios with this plugin, it clearly states what we support (Icinga Classic UI and Icinga 2 API).
