### ISSUE TITLE
Version 0.9.4 is still not in Chrome Web Store

### ISSUE THREAD

**Issue by mstockin** [bashgeek/icinga-multi-status#29]
In https://chromewebstore.google.com/detail/icinga-multi-status still there is only version 0.9.3 for download. I'm waiting for a long time now, but there is no change.
This is a problem if your are affected by the bug, that is fixed in 0.9.4, as there is also no possibility to download a version below 0.9.3 as a workaround.

**Comment by bashgeek** [comment]
I could've sworn I uploaded it there, too, in September. Anyway, uploaded it again and seems to be published now.

Thanks for reporting and sorry for the inconvenience.
