### ISSUE TITLE
Support for Manifest V3

### ISSUE THREAD

**Issue by AlexanderS** [bashgeek/icinga-multi-status#30]
The extension should support Manifest V3 because Chrome actively stated to block Manifest V2 extensions.

Possible the only required change is the migration of the background page to a service worker.

**Comment by bashgeek** [comment]
It actually requires quite a bit of refactoring to make this work properly with the whole feature set - and also still work in both browsers, Chrome and Firefox.

I'll try to have a deeper look into this around the end of the year or Q1 of next year.

**Comment by AlexanderS** [comment]
I think, this does not yet work reliable. If I have read the code correctly, you keep the state as global variables inside the service worker. This does not work, as the browser will stop and restart the service worker when ever it seems appropriate. 

You need to keep the persistent data with one of the available storage APIs: https://developer.chrome.com/docs/extensions/develop/concepts/service-workers/lifecycle#persist-data

**Comment by bashgeek** [comment]
Thanks, we published a new version, that is currently being reviewed.
