### ISSUE TITLE
Icinga Multi Status on Firefox 133.0.3 does not display small icons above the extension in the toolbar

### ISSUE THREAD

**Issue by tachtler** [bashgeek/icinga-multi-status#33]
Hello,

when restarting Firefox, the extension **Icinga Multi Status** is displayed in the toolbar in Firefox,
but the **_small icons above the toolbar icon are missing_**.  

This is only displayed after I have **_deactivated and reactivated_** Icinga Multi Status in Firefox under Extensions & Themes.

> before deactivation → ![image](https://github.com/user-attachments/assets/3b54c3bf-6fe4-4093-ab75-ff115928d1ce)
> after reactivation → ![image](https://github.com/user-attachments/assets/6e001f44-1a1e-4848-9325-5456d601c0c4)

Any idea why this could be?

**OS**: ArchLinux
**Firefox**: (package - pacman installation) 133.0.3 (64-bit)

Thanks in advance!

**Comment by tachtler** [comment]
Hello,

I've found in debugging mode inside Firefox following "Warnings":

`Reading manifest: Warning processing background.service_worker: An unexpected property was found in the WebExtension manifest.`

`Reading manifest: Warning processing permissions: Error processing permissions.4: Value "offscreen" must either: must either [must either [be one of ["idle"], be one of ["menus.overrideContext"], be one of ["search"], be one of ["activeTab"], be one of ["cookies"], be one of ["scripting"], or be one of ["webRequest", "webRequestAuthProvider", "webRequestBlocking", "webRequestFilterResponse", "webRequestFilterResponse.serviceWorkerScript"]], must either [be one of ["mozillaAddons"], be one of ["normandyAddonStudy"], be one of ["activityLog"], be one of ["networkStatus"], or be one of ["telemetry"]], be one of ["alarms", "storage", "unlimitedStorage"], be one of ["captivePortal"], be one of ["identity"], be one of ["menus", "contextMenus"], be one of ["geckoProfiler"], be one of ["contextualIdentities"], be one of ["declarativeNetRequestWithHostAccess"], be one of ["dns"], or be one of ["theme"]], must either [must either [be one of ["idle"], be one of ["menus.overrideContext"], be one of ["search"], be one of ["activeTab"], be one of ["cookies"], be one of ["scripting"], or be one of ["webRequest", "webRequestAuthProvider", "webRequestBlocking", "webRequestFilterResponse", "webRequestFilterResponse.serviceWorkerScript"]], be one of ["clipboardRead", "clipboardWrite", "geolocation", "notifications"], be one of ["bookmarks"], be one of ["browsingData"], be one of ["devtools"], be one of ["find"], be one of ["history"], be one of ["pkcs11"], be one of ["sessions"], be one of ["tabs", "tabHide"], be one of ["topSites"], be one of ["browserSettings"], be one of ["declarativeNetRequestFeedback"], be one of ["downloads", "downloads.open"], be one of ["management"], be one of ["privacy"], be one of ["proxy"], be one of ["nativeMessaging"], or be one of ["webNavigation"]], be one of ["declarativeNetRequest"], or match the pattern /^experiments(\.\w+)+$/`

Please, can you help!

**Comment by bashgeek** [comment]
We just published a small update regarding this with 1.0.3, it should work better now. Nobody here ever closes their browser, so we never noticed this behavior.

You can disregard those warnings, they come from the cross-compatibility with Chrome.
