### ISSUE TITLE
error 404 on click at hostname because it links on icinga v1 ressource

### ISSUE THREAD

**Issue by ulfkosack** [bashgeek/icinga-multi-status#4]
{"error":404.0,"status":"The requested path 'cgi-bin/extinfo.cgi' could not be found or the request method is not valid for this path."}

I use your plugin with icinga2 API. The connection is functionally and shows hosts and services. The link on hostname in the plugin window goes to https://<icinga2srv>:5665/cgi-bin/extinfo.cgi..... 

Could you make it configurable to input the Webserver-URL for the Browser?

**Comment by bashgeek** [comment]
Thanks for reporting this, I already realised this myself.

Added the option and pushed a new release to Chrome store (0.3.1) which should be available soon.
