### ISSUE TITLE
Add Schedule one hour and Acknowledge Button

### ISSUE THREAD

**Issue by frostynova** [bashgeek/icinga-multi-status#9]
It will better to have these buttons, for quickly schedule down or ack some services and hosts.

**Comment by bashgeek** [comment]
Oh, forgot to reply here. The one-hour schedule is already in there since a few versions now. An acknowledge button is definitely something we'll be working on.

**Comment by bashgeek** [comment]
Well, only took 3.5 years! :-) Added an acknowledge and recheck button with the last update.
